/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod'

/**
 * Creates a new user
 * @summary Sign Up
 */
export const signUpBody = zod.object({
  username: zod.string(),
  email: zod.string(),
  password: zod.string(),
})

export const signUpResponse = zod.object({
  message: zod.string().optional(),
  data: zod
    .object({
      id: zod.number().optional(),
    })
    .optional(),
  status: zod.number().optional(),
})

/**
 * Signs in a user and returns an auth token
 * @summary Sign In
 */
export const signInBody = zod.object({
  email: zod.string(),
  password: zod.string(),
})

export const signInResponse = zod.object({
  message: zod.string().optional(),
  data: zod
    .object({
      token: zod.string().optional(),
      id: zod.number().optional(),
    })
    .optional(),
  status: zod.number().optional(),
})

/**
 * Signs out a user and deletes the auth token
 * @summary Sign Out
 */
export const signOutResponse = zod.object({
  message: zod.string().optional(),
  data: zod.string().optional(),
  status: zod.number().optional(),
})

/**
 * Changes the password of the authenticated user
 * @summary Change Password
 */
export const changePasswordBody = zod.object({
  current_password: zod.string(),
  new_password: zod.string(),
})

export const changePasswordResponse = zod.object({
  message: zod.string().optional(),
  data: zod.string().optional(),
  status: zod.number().optional(),
})

/**
 * Sends a verification code to the authenticated user's email
 * @summary Send Email Verification Code
 */
export const sendEmailVerificationCodeResponse = zod.object({
  message: zod.string().optional(),
  data: zod.string().optional(),
  status: zod.number().optional(),
})

/**
 * Verifies the email verification code
 * @summary Verify Email Code
 */
export const verifyEmailCodeBody = zod.object({
  code: zod.string(),
})

export const verifyEmailCodeResponse = zod.object({
  message: zod.string().optional(),
  data: zod.string().optional(),
  status: zod.number().optional(),
})

/**
 * Signs in an admin user and returns an auth token
 * @summary Admin Sign In
 */
export const adminSignInBody = zod.object({
  email: zod.string(),
  password: zod.string(),
})

export const adminSignInResponse = zod.object({
  message: zod.string().optional(),
  data: zod
    .object({
      token: zod.string().optional(),
      id: zod.number().optional(),
    })
    .optional(),
  status: zod.number().optional(),
})
