/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod'

/**
 * Retrieve a list of artworks favorites by the currently authenticated user
 * @summary List Authenticated User Favorite Artworks
 */
export const listAuthenticatedUserFavoriteArtworksResponse = zod.object({
  data: zod
    .array(
      zod.object({
        id: zod.number().optional(),
        title: zod.string().optional(),
        description: zod.string().optional(),
        status: zod.string().optional(),
        user_id: zod.number().optional(),
        created_at: zod.string().optional(),
        updated_at: zod.string().optional(),
        artwork_likes_count: zod.number().optional(),
        artwork_comments_count: zod.number().optional(),
        artwork_main_photo_path: zod.string().optional(),
      })
    )
    .optional(),
})

/**
 * Mark an artwork as favorite
 * @summary Mark Artwork As Favorite
 */
export const markArtworkAsFavoriteResponse = zod.object({
  data: zod
    .object({
      id: zod.number().optional(),
      artwork_id: zod.number().optional(),
      user_id: zod.number().optional(),
      created_at: zod.string().optional(),
      updated_at: zod.string().optional(),
    })
    .optional(),
})

/**
 * Check if the currently authenticated user is favoriting an artwork
 * @summary Check if Authenticated User is Favoriting
 */
export const checkIfAuthenticatedUserIsFavoritingResponse = zod.object({
  message: zod.string().optional(),
  data: zod.boolean().optional(),
  status: zod.number().optional(),
})
