/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import {
  ACCEPTED_IMAGE_TYPES,
  MAX_FILE_SIZE,
  MAX_WORDS,
  MIN_WORDS,
} from '@/lib/constants'
import { z as zod } from 'zod'

/**
 * Create a new artwork
 * @summary Create Artwork
 */
export const createArtworkBody = zod.object({
  title: zod.string().max(255),
  description: zod.string().refine(
    (value) => {
      if (!value) return true
      const wordCount = value.trim().split(/\s+/).length
      return wordCount > MIN_WORDS && wordCount <= MAX_WORDS
    },
    {
      message: `Description's words' count must be between ${MIN_WORDS} and ${MAX_WORDS} words.`,
    }
  ),
  tags: zod
    .set(
      zod.enum([
        'painting',
        'graphic',
        'sculpture',
        'folk art',
        'textile',
        'ceramics',
        'stained glass windows',
        'beads',
        'paper',
        'glass',
        'dolls',
        'jewellery',
        'fresco',
        'metal',
        'mosaic',
      ])
    )
    .min(1)
    .max(3),
  photos: zod
    .object({
      file: zod
        .instanceof(File)
        .refine((f) => f.size < MAX_FILE_SIZE, '5 MB is the max upload size.')
        .refine(
          (file) => ACCEPTED_IMAGE_TYPES.includes(file.type),
          'Only .jpg, .jpeg, .png and .webp formats are supported.'
        ),
      is_main: zod.boolean(),
    })
    .array()
    .min(1)
    .max(10),
})

/**
 * Update an artwork draft
 * @summary Update Artwork Draft
 */
export const updateArtworkDraftBody = zod.object({
  title: zod.string().max(255).optional(),
  description: zod
    .string()
    .optional()
    .refine(
      (value) => {
        if (!value) return true
        const wordCount = value.trim().split(/\s+/).length
        return wordCount > MIN_WORDS && wordCount <= MAX_WORDS
      },
      {
        message: `Description's words' count must be between ${MIN_WORDS} and ${MAX_WORDS} words.`,
      }
    ),
  tags: zod
    .set(
      zod.enum([
        'painting',
        'graphic',
        'sculpture',
        'folk art',
        'textile',
        'ceramics',
        'stained glass windows',
        'beads',
        'paper',
        'glass',
        'dolls',
        'jewellery',
        'fresco',
        'metal',
        'mosaic',
      ])
    )
    .min(1)
    .max(3)
    .optional(),
})
