/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod'

/**
 * Creates a new user
 * @summary Sign Up
 */
export const signUpBody = zod
  .object({
    username: zod
      .string()
      .min(3)
      .max(255)
      .regex(
        /^[a-zA-Z0-9_-]+$/,
        'Username can only contain letters, numbers, dashes, and underscores'
      ),
    email: zod.string().email(),
    password: zod.string().min(8),
    password_confirmation: zod.string().min(8),
  })
  .refine(
    (value) => {
      return value.password === value.password_confirmation
    },
    {
      message: 'Passwords does not match.',
      path: ['password_confirmation'],
    }
  )

/**
 * Signs in a user and returns an auth token
 * @summary Sign In
 */
export const signInBody = zod.object({
  email: zod.string().email(),
  password: zod.string().min(8),
})

/**
 * Sends a reset password link to the user's email
 * @summary Send Reset Password Link
 */
export const sendResetPasswordLinkBody = zod.object({
  email: zod.string().email(),
})

/**
 * Resets the password of the user
 * @summary Reset Password
 */
export const resetPasswordBody = zod
  .object({
    token: zod.string(),
    email: zod.string().email(),
    password: zod.string().min(8),
    password_confirmation: zod.string().min(8),
  })
  .refine(
    (value) => {
      return value.password === value.password_confirmation
    },
    {
      message: 'Passwords does not match.',
      path: ['password_confirmation'],
    }
  )

/**
 * Changes the password of the authenticated user
 * @summary Change Password
 */
export const changePasswordBody = zod
  .object({
    current_password: zod.string().min(8),
    new_password: zod.string().min(8),
    new_password_confirmation: zod.string().min(8),
  })
  .refine(
    (value) => {
      return value.new_password === value.new_password_confirmation
    },
    {
      message: 'Passwords does not match.',
      path: ['password_confirmation'],
    }
  )
