/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import {
  ACCEPTED_IMAGE_TYPES,
  MAX_FILE_SIZE,
  MAX_WORDS,
  MIN_WORDS,
} from '@/lib/constants'
import { z as zod } from 'zod'

/**
 * Update the currently authenticated user
 * @summary Update Authenticated User
 */
export const updateAuthenticatedUserBody = zod.object({
  username: zod.string().max(255).optional(),
  first_name: zod.string().max(255).optional(),
  last_name: zod.string().max(255).optional(),
  email: zod.string().email().optional(),
  country: zod.string().optional(),
  bio: zod
    .string()
    .optional()
    .refine(
      (value) => {
        if (!value) return true
        const wordCount = value.trim().split(/\s+/).length
        return wordCount > MIN_WORDS && wordCount <= MAX_WORDS
      },
      {
        message: `Bio's words' count must be between ${MIN_WORDS} and ${MAX_WORDS} words.`,
      }
    ),
  photo: zod
    .instanceof(File)
    .refine((f) => f.size < MAX_FILE_SIZE, '5 MB is the max upload size.')
    .refine(
      (file) => ACCEPTED_IMAGE_TYPES.includes(file.type),
      'Only .jpg, .jpeg, .png and .webp formats are supported.'
    ),
})
