/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod'

/**
 * Post a comment on an artwork
 * @summary Post Artwork Comment
 */
export const postArtworkCommentBody = zod.object({
  comment_text: zod.string(),
})

export const postArtworkCommentResponse = zod.object({
  data: zod
    .object({
      id: zod.number().optional(),
      comment_text: zod.string().optional(),
      artwork_id: zod.number().optional(),
      user_id: zod.number().optional(),
      created_at: zod.string().optional(),
      updated_at: zod.string().optional(),
    })
    .optional(),
})

/**
 * Update a comment on an artwork
 * @summary Update Artwork Comment
 */
export const updateArtworkCommentBody = zod.object({
  comment_text: zod.string(),
})

export const updateArtworkCommentResponse = zod.object({
  data: zod
    .object({
      id: zod.number().optional(),
      comment_text: zod.string().optional(),
      artwork_id: zod.number().optional(),
      user_id: zod.number().optional(),
      created_at: zod.string().optional(),
      updated_at: zod.string().optional(),
    })
    .optional(),
})
