/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod'

/**
 * Retrieve the number of likes an artist has received by tag
 * @summary List User Received Likes Count by Tag
 */
export const listUserReceivedLikesCountByTagResponse = zod.object({
  message: zod.string().optional(),
  data: zod
    .array(
      zod.object({
        tag_name: zod.string().optional(),
        total_likes: zod.number().optional(),
      })
    )
    .optional(),
  status: zod.number().optional(),
})

/**
 * Retrieve the total number of likes an artist has received
 * @summary Show User Received Likes Count
 */
export const showUserReceivedLikesCountResponse = zod.object({
  message: zod.string().optional(),
  data: zod.number().optional(),
  status: zod.number().optional(),
})

/**
 * Like an artwork
 * @summary Like Artwork
 */
export const likeArtworkResponse = zod.object({
  data: zod
    .object({
      id: zod.number().optional(),
      artwork_id: zod.number().optional(),
      user_id: zod.number().optional(),
      created_at: zod.string().optional(),
      updated_at: zod.string().optional(),
    })
    .optional(),
})
