/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import axios from '@/lib/axios'
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios'
import type {
  CheckIfAuthenticatedUserIsFavoriting200,
  CheckIfAuthenticatedUserIsFavoriting401,
  CheckIfAuthenticatedUserIsFavoriting404,
  ListAuthenticatedUserFavoriteArtworks200,
  ListAuthenticatedUserFavoriteArtworks401,
  MarkArtworkAsFavorite200,
  MarkArtworkAsFavorite401,
  MarkArtworkAsFavorite403,
  MarkArtworkAsFavorite404,
  RemoveArtworkFromFavorites401,
  RemoveArtworkFromFavorites403,
  RemoveArtworkFromFavorites404,
} from '.././model'

/**
 * Retrieve a list of artworks favorites by the currently authenticated user
 * @summary List Authenticated User Favorite Artworks
 */
export const listAuthenticatedUserFavoriteArtworks = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<ListAuthenticatedUserFavoriteArtworks200>> => {
  return axios.get(`/api/v1/users/me/favorites/artworks`, options)
}

export const getListAuthenticatedUserFavoriteArtworksQueryKey = () => {
  return [`/api/v1/users/me/favorites/artworks`] as const
}

export const getListAuthenticatedUserFavoriteArtworksQueryOptions = <
  TData = Awaited<ReturnType<typeof listAuthenticatedUserFavoriteArtworks>>,
  TError = AxiosError<ListAuthenticatedUserFavoriteArtworks401>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof listAuthenticatedUserFavoriteArtworks>>,
      TError,
      TData
    >
  >
  axios?: AxiosRequestConfig
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getListAuthenticatedUserFavoriteArtworksQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listAuthenticatedUserFavoriteArtworks>>
  > = ({ signal }) =>
    listAuthenticatedUserFavoriteArtworks({ signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listAuthenticatedUserFavoriteArtworks>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAuthenticatedUserFavoriteArtworksQueryResult = NonNullable<
  Awaited<ReturnType<typeof listAuthenticatedUserFavoriteArtworks>>
>
export type ListAuthenticatedUserFavoriteArtworksQueryError =
  AxiosError<ListAuthenticatedUserFavoriteArtworks401>

export function useListAuthenticatedUserFavoriteArtworks<
  TData = Awaited<ReturnType<typeof listAuthenticatedUserFavoriteArtworks>>,
  TError = AxiosError<ListAuthenticatedUserFavoriteArtworks401>,
>(options: {
  query: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof listAuthenticatedUserFavoriteArtworks>>,
      TError,
      TData
    >
  > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof listAuthenticatedUserFavoriteArtworks>>,
        TError,
        Awaited<ReturnType<typeof listAuthenticatedUserFavoriteArtworks>>
      >,
      'initialData'
    >
  axios?: AxiosRequestConfig
}): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useListAuthenticatedUserFavoriteArtworks<
  TData = Awaited<ReturnType<typeof listAuthenticatedUserFavoriteArtworks>>,
  TError = AxiosError<ListAuthenticatedUserFavoriteArtworks401>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof listAuthenticatedUserFavoriteArtworks>>,
      TError,
      TData
    >
  > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof listAuthenticatedUserFavoriteArtworks>>,
        TError,
        Awaited<ReturnType<typeof listAuthenticatedUserFavoriteArtworks>>
      >,
      'initialData'
    >
  axios?: AxiosRequestConfig
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useListAuthenticatedUserFavoriteArtworks<
  TData = Awaited<ReturnType<typeof listAuthenticatedUserFavoriteArtworks>>,
  TError = AxiosError<ListAuthenticatedUserFavoriteArtworks401>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof listAuthenticatedUserFavoriteArtworks>>,
      TError,
      TData
    >
  >
  axios?: AxiosRequestConfig
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary List Authenticated User Favorite Artworks
 */

export function useListAuthenticatedUserFavoriteArtworks<
  TData = Awaited<ReturnType<typeof listAuthenticatedUserFavoriteArtworks>>,
  TError = AxiosError<ListAuthenticatedUserFavoriteArtworks401>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof listAuthenticatedUserFavoriteArtworks>>,
      TError,
      TData
    >
  >
  axios?: AxiosRequestConfig
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions =
    getListAuthenticatedUserFavoriteArtworksQueryOptions(options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Mark an artwork as favorite
 * @summary Mark Artwork As Favorite
 */
export const markArtworkAsFavorite = (
  artworkId: number,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<MarkArtworkAsFavorite200>> => {
  return axios.post(
    `/api/v1/artworks/${artworkId}/favorites`,
    undefined,
    options
  )
}

export const getMarkArtworkAsFavoriteMutationOptions = <
  TError = AxiosError<
    | MarkArtworkAsFavorite401
    | MarkArtworkAsFavorite403
    | MarkArtworkAsFavorite404
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof markArtworkAsFavorite>>,
    TError,
    { artworkId: number },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof markArtworkAsFavorite>>,
  TError,
  { artworkId: number },
  TContext
> => {
  const mutationKey = ['markArtworkAsFavorite']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof markArtworkAsFavorite>>,
    { artworkId: number }
  > = (props) => {
    const { artworkId } = props ?? {}

    return markArtworkAsFavorite(artworkId, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type MarkArtworkAsFavoriteMutationResult = NonNullable<
  Awaited<ReturnType<typeof markArtworkAsFavorite>>
>

export type MarkArtworkAsFavoriteMutationError = AxiosError<
  MarkArtworkAsFavorite401 | MarkArtworkAsFavorite403 | MarkArtworkAsFavorite404
>

/**
 * @summary Mark Artwork As Favorite
 */
export const useMarkArtworkAsFavorite = <
  TError = AxiosError<
    | MarkArtworkAsFavorite401
    | MarkArtworkAsFavorite403
    | MarkArtworkAsFavorite404
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof markArtworkAsFavorite>>,
    TError,
    { artworkId: number },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationResult<
  Awaited<ReturnType<typeof markArtworkAsFavorite>>,
  TError,
  { artworkId: number },
  TContext
> => {
  const mutationOptions = getMarkArtworkAsFavoriteMutationOptions(options)

  return useMutation(mutationOptions)
}
/**
 * Remove an artwork from favorites
 * @summary Remove Artwork From Favorites
 */
export const removeArtworkFromFavorites = (
  artworkId: number,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<string>> => {
  return axios.delete(`/api/v1/artworks/${artworkId}/favorites`, options)
}

export const getRemoveArtworkFromFavoritesMutationOptions = <
  TError = AxiosError<
    | RemoveArtworkFromFavorites401
    | RemoveArtworkFromFavorites403
    | RemoveArtworkFromFavorites404
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeArtworkFromFavorites>>,
    TError,
    { artworkId: number },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof removeArtworkFromFavorites>>,
  TError,
  { artworkId: number },
  TContext
> => {
  const mutationKey = ['removeArtworkFromFavorites']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof removeArtworkFromFavorites>>,
    { artworkId: number }
  > = (props) => {
    const { artworkId } = props ?? {}

    return removeArtworkFromFavorites(artworkId, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type RemoveArtworkFromFavoritesMutationResult = NonNullable<
  Awaited<ReturnType<typeof removeArtworkFromFavorites>>
>

export type RemoveArtworkFromFavoritesMutationError = AxiosError<
  | RemoveArtworkFromFavorites401
  | RemoveArtworkFromFavorites403
  | RemoveArtworkFromFavorites404
>

/**
 * @summary Remove Artwork From Favorites
 */
export const useRemoveArtworkFromFavorites = <
  TError = AxiosError<
    | RemoveArtworkFromFavorites401
    | RemoveArtworkFromFavorites403
    | RemoveArtworkFromFavorites404
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeArtworkFromFavorites>>,
    TError,
    { artworkId: number },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationResult<
  Awaited<ReturnType<typeof removeArtworkFromFavorites>>,
  TError,
  { artworkId: number },
  TContext
> => {
  const mutationOptions = getRemoveArtworkFromFavoritesMutationOptions(options)

  return useMutation(mutationOptions)
}
/**
 * Check if the currently authenticated user is favoriting an artwork
 * @summary Check if Authenticated User is Favoriting
 */
export const checkIfAuthenticatedUserIsFavoriting = (
  artworkId: number,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<CheckIfAuthenticatedUserIsFavoriting200>> => {
  return axios.get(
    `/api/v1/artworks/${artworkId}/favorites/is-favoriting`,
    options
  )
}

export const getCheckIfAuthenticatedUserIsFavoritingQueryKey = (
  artworkId: number
) => {
  return [`/api/v1/artworks/${artworkId}/favorites/is-favoriting`] as const
}

export const getCheckIfAuthenticatedUserIsFavoritingQueryOptions = <
  TData = Awaited<ReturnType<typeof checkIfAuthenticatedUserIsFavoriting>>,
  TError = AxiosError<
    | CheckIfAuthenticatedUserIsFavoriting401
    | CheckIfAuthenticatedUserIsFavoriting404
  >,
>(
  artworkId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof checkIfAuthenticatedUserIsFavoriting>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getCheckIfAuthenticatedUserIsFavoritingQueryKey(artworkId)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof checkIfAuthenticatedUserIsFavoriting>>
  > = ({ signal }) =>
    checkIfAuthenticatedUserIsFavoriting(artworkId, { signal, ...axiosOptions })

  return {
    queryKey,
    queryFn,
    enabled: !!artworkId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof checkIfAuthenticatedUserIsFavoriting>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CheckIfAuthenticatedUserIsFavoritingQueryResult = NonNullable<
  Awaited<ReturnType<typeof checkIfAuthenticatedUserIsFavoriting>>
>
export type CheckIfAuthenticatedUserIsFavoritingQueryError = AxiosError<
  | CheckIfAuthenticatedUserIsFavoriting401
  | CheckIfAuthenticatedUserIsFavoriting404
>

export function useCheckIfAuthenticatedUserIsFavoriting<
  TData = Awaited<ReturnType<typeof checkIfAuthenticatedUserIsFavoriting>>,
  TError = AxiosError<
    | CheckIfAuthenticatedUserIsFavoriting401
    | CheckIfAuthenticatedUserIsFavoriting404
  >,
>(
  artworkId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof checkIfAuthenticatedUserIsFavoriting>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof checkIfAuthenticatedUserIsFavoriting>>,
          TError,
          Awaited<ReturnType<typeof checkIfAuthenticatedUserIsFavoriting>>
        >,
        'initialData'
      >
    axios?: AxiosRequestConfig
  }
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useCheckIfAuthenticatedUserIsFavoriting<
  TData = Awaited<ReturnType<typeof checkIfAuthenticatedUserIsFavoriting>>,
  TError = AxiosError<
    | CheckIfAuthenticatedUserIsFavoriting401
    | CheckIfAuthenticatedUserIsFavoriting404
  >,
>(
  artworkId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof checkIfAuthenticatedUserIsFavoriting>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof checkIfAuthenticatedUserIsFavoriting>>,
          TError,
          Awaited<ReturnType<typeof checkIfAuthenticatedUserIsFavoriting>>
        >,
        'initialData'
      >
    axios?: AxiosRequestConfig
  }
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useCheckIfAuthenticatedUserIsFavoriting<
  TData = Awaited<ReturnType<typeof checkIfAuthenticatedUserIsFavoriting>>,
  TError = AxiosError<
    | CheckIfAuthenticatedUserIsFavoriting401
    | CheckIfAuthenticatedUserIsFavoriting404
  >,
>(
  artworkId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof checkIfAuthenticatedUserIsFavoriting>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  }
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Check if Authenticated User is Favoriting
 */

export function useCheckIfAuthenticatedUserIsFavoriting<
  TData = Awaited<ReturnType<typeof checkIfAuthenticatedUserIsFavoriting>>,
  TError = AxiosError<
    | CheckIfAuthenticatedUserIsFavoriting401
    | CheckIfAuthenticatedUserIsFavoriting404
  >,
>(
  artworkId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof checkIfAuthenticatedUserIsFavoriting>>,
        TError,
        TData
      >
    >
    axios?: AxiosRequestConfig
  }
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getCheckIfAuthenticatedUserIsFavoritingQueryOptions(
    artworkId,
    options
  )

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}
