/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod'

/**
 * Retrieve a list of countries
 * @summary List Countries
 */
export const listCountriesResponse = zod.object({
  data: zod
    .array(
      zod.object({
        id: zod.number().optional(),
        name: zod.string().optional(),
        created_at: zod.string().optional(),
        updated_at: zod.string().optional(),
      })
    )
    .optional(),
})
