/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod'

/**
 * Upload photos to an artwork draft
 * @summary Upload Artwork Photos
 */
export const uploadArtworkPhotosResponse = zod.object({
  data: zod
    .array(
      zod.object({
        id: zod.number().optional(),
        path: zod.string().optional(),
        is_main: zod.number().optional(),
        artwork_id: zod.number().optional(),
        created_at: zod.string().optional(),
        updated_at: zod.string().optional(),
      })
    )
    .optional(),
})

/**
 * Set an artwork photo as the main photo of the artwork
 * @summary Set Artwork Photo As Main
 */
export const setArtworkPhotoAsMainResponse = zod.object({
  data: zod
    .object({
      id: zod.number().optional(),
      path: zod.string().optional(),
      is_main: zod.number().optional(),
      artwork_id: zod.number().optional(),
      created_at: zod.string().optional(),
      updated_at: zod.string().optional(),
    })
    .optional(),
})

/**
 * Delete an artwork photo
 * @summary Delete Artwork Photo
 */
export const deleteArtworkPhotoResponse = zod.object({
  message: zod.string().optional(),
  data: zod.string().optional(),
  status: zod.number().optional(),
})
