/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { AdminSignIn200Data } from './adminSignIn200Data'

export type AdminSignIn200 = {
  data?: AdminSignIn200Data
  message?: string
  status?: number
}
