/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type ChangePasswordBody = {
  /**
   * The current password of the user.
   */
  current_password: string
  /**
   * The new password of the user. Must be at least 8 characters.
   */
  new_password: string
}
