/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { CheckIfUnreadNotificationsExist200Data } from './checkIfUnreadNotificationsExist200Data'

export type CheckIfUnreadNotificationsExist200 = {
  message?: string
  data?: CheckIfUnreadNotificationsExist200Data
  status?: number
}
