/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { CreateArtwork200Data } from './createArtwork200Data'

export type CreateArtwork200 = {
  data?: CreateArtwork200Data
}
