/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { FollowUser200Data } from './followUser200Data'

export type FollowUser200 = {
  data?: FollowUser200Data
}
