/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type FollowUser200Data = {
  created_at?: string
  followed_id?: number
  follower_id?: number
  id?: number
  updated_at?: string
}
