/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type LikeArtwork200Data = {
  artwork_id?: number
  created_at?: string
  id?: number
  updated_at?: string
  user_id?: number
}
