/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListAuthenticatedUserNotifications200OneOfData } from './listAuthenticatedUserNotifications200OneOfData'

/**
 * Authenticated as admin
 */
export type ListAuthenticatedUserNotifications200OneOf = {
  data?: ListAuthenticatedUserNotifications200OneOfData
  message?: string
  status?: number
}
