/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListCountries200DataItem } from './listCountries200DataItem'

export type ListCountries200 = {
  data?: ListCountries200DataItem[]
}
