/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type ListUsersFilterTag =
  (typeof ListUsersFilterTag)[keyof typeof ListUsersFilterTag]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListUsersFilterTag = {
  painting: 'painting',
  graphic: 'graphic',
  sculpture: 'sculpture',
  folk_art: 'folk art',
  textile: 'textile',
  ceramics: 'ceramics',
  stained_glass_windows: 'stained glass windows',
  beads: 'beads',
  paper: 'paper',
  glass: 'glass',
  dolls: 'dolls',
  jewellery: 'jewellery',
  fresco: 'fresco',
  metal: 'metal',
  mosaic: 'mosaic',
} as const
