/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListArtistVerificationRequests200MetaLinksItem } from './listArtistVerificationRequests200MetaLinksItem'

export type ListArtistVerificationRequests200Meta = {
  current_page?: number
  from?: number
  last_page?: number
  links?: ListArtistVerificationRequests200MetaLinksItem[]
  path?: string
  per_page?: number
  to?: number
  total?: number
}
