/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type ListUserPublishedArtworksSort =
  (typeof ListUserPublishedArtworksSort)[keyof typeof ListUserPublishedArtworksSort]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListUserPublishedArtworksSort = {
  rising: 'rising',
  new: 'new',
  popular: 'popular',
  trending: 'trending',
} as const
