/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListAuthenticatedUserNotifications400OneOf } from './listAuthenticatedUserNotifications400OneOf'
import type { ListAuthenticatedUserNotifications400OneOfTwo } from './listAuthenticatedUserNotifications400OneOfTwo'

export type ListAuthenticatedUserNotifications400 =
  | ListAuthenticatedUserNotifications400OneOf
  | ListAuthenticatedUserNotifications400OneOfTwo
