/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListTags200DataItem } from './listTags200DataItem'

export type ListTags200 = {
  data?: ListTags200DataItem[]
}
