/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListAuthenticatedUserNotifications200OneOfDataDataItem } from './listAuthenticatedUserNotifications200OneOfDataDataItem'
import type { ListAuthenticatedUserNotifications200OneOfDataLinksItem } from './listAuthenticatedUserNotifications200OneOfDataLinksItem'

export type ListAuthenticatedUserNotifications200OneOfData = {
  current_page?: number
  data?: ListAuthenticatedUserNotifications200OneOfDataDataItem[]
  first_page_url?: string
  from?: number
  last_page?: number
  last_page_url?: string
  links?: ListAuthenticatedUserNotifications200OneOfDataLinksItem[]
  next_page_url?: string
  path?: string
  per_page?: number
  prev_page_url?: string
  to?: number
  total?: number
}
