/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type ListAuthenticatedUserArtworksFilterStatus =
  (typeof ListAuthenticatedUserArtworksFilterStatus)[keyof typeof ListAuthenticatedUserArtworksFilterStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListAuthenticatedUserArtworksFilterStatus = {
  draft: 'draft',
  published: 'published',
} as const
