/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListAuthenticatedUserFollowers200DataItem } from './listAuthenticatedUserFollowers200DataItem'

export type ListAuthenticatedUserFollowers200 = {
  data?: ListAuthenticatedUserFollowers200DataItem[]
}
