/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type ListUsersFilterVerified =
  (typeof ListUsersFilterVerified)[keyof typeof ListUsersFilterVerified]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListUsersFilterVerified = {
  NUMBER_1: 1,
  NUMBER_0: 0,
} as const
