/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListAuthenticatedUserFavoriteArtworks200DataItem } from './listAuthenticatedUserFavoriteArtworks200DataItem'

export type ListAuthenticatedUserFavoriteArtworks200 = {
  data?: ListAuthenticatedUserFavoriteArtworks200DataItem[]
}
