/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListAuthenticatedUserNotificationsFilterNotificationType } from './listAuthenticatedUserNotificationsFilterNotificationType'
import type { ListAuthenticatedUserNotificationsFilterReadStatus } from './listAuthenticatedUserNotificationsFilterReadStatus'

export type ListAuthenticatedUserNotificationsParams = {
  /**
   * Filter notification by notification type.
   */
  'filter[notificationType]'?: ListAuthenticatedUserNotificationsFilterNotificationType
  /**
   * Filter notification by read and unread.
   */
  'filter[readStatus]'?: ListAuthenticatedUserNotificationsFilterReadStatus
  /**
   * The page number to fetch.
   */
  page?: number
  /**
   * The number of records to fetch per page.
   */
  perPage?: number
}
