/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListAuthenticatedUserNotifications200OneOfDataDataItemData } from './listAuthenticatedUserNotifications200OneOfDataDataItemData'

export type ListAuthenticatedUserNotifications200OneOfDataDataItem = {
  id?: string
  type?: string
  notifiable_type?: string
  notifiable_id?: number
  data?: ListAuthenticatedUserNotifications200OneOfDataDataItemData
  read_at?: string
  created_at?: string
  updated_at?: string
}
