/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListAuthenticatedUserNotifications200OneOfSevenDataDataItemData } from './listAuthenticatedUserNotifications200OneOfSevenDataDataItemData'

export type ListAuthenticatedUserNotifications200OneOfSevenDataDataItem = {
  created_at?: string
  data?: ListAuthenticatedUserNotifications200OneOfSevenDataDataItemData
  id?: string
  notifiable_id?: number
  notifiable_type?: string
  read_at?: string
  type?: string
  updated_at?: string
}
