/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListAuthenticatedUserArtworks200DataItem } from './listAuthenticatedUserArtworks200DataItem'
import type { ListAuthenticatedUserArtworks200Links } from './listAuthenticatedUserArtworks200Links'
import type { ListAuthenticatedUserArtworks200Meta } from './listAuthenticatedUserArtworks200Meta'

export type ListAuthenticatedUserArtworks200 = {
  data?: ListAuthenticatedUserArtworks200DataItem[]
  links?: ListAuthenticatedUserArtworks200Links
  meta?: ListAuthenticatedUserArtworks200Meta
}
