/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListAuthenticatedUserNotifications200OneOfSevenData } from './listAuthenticatedUserNotifications200OneOfSevenData'

/**
 * Authenticated as artist
 */
export type ListAuthenticatedUserNotifications200OneOfSeven = {
  data?: ListAuthenticatedUserNotifications200OneOfSevenData
  message?: string
  status?: number
}
