/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListAuthenticatedUserArtworksFilterStatus } from './listAuthenticatedUserArtworksFilterStatus'

export type ListAuthenticatedUserArtworksParams = {
  /**
   * Filter artworks by status.
   */
  'filter[status]'?: ListAuthenticatedUserArtworksFilterStatus
  /**
   * The page number to fetch.
   */
  page?: number
  /**
   * The number of records to fetch per page.
   */
  perPage?: number
}
