/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListUserPublishedArtworksFilterTag } from './listUserPublishedArtworksFilterTag'
import type { ListUserPublishedArtworksSort } from './listUserPublishedArtworksSort'

export type ListUserPublishedArtworksParams = {
  /**
   * Filter artworks by tag.
   */
  'filter[tag]'?: ListUserPublishedArtworksFilterTag
  /**
   * Sort artworks.
   */
  sort?: ListUserPublishedArtworksSort
  /**
   * The page number to fetch.
   */
  page?: string
  /**
   * The number of records to fetch per page.
   */
  perPage?: number
}
