/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListUserArtworkTags200DataItem } from './listUserArtworkTags200DataItem'

export type ListUserArtworkTags200 = {
  data?: ListUserArtworkTags200DataItem[]
  message?: string
  status?: number
}
