/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListAuthenticatedUserArtworks200DataItemArtworkPhotosItem } from './listAuthenticatedUserArtworks200DataItemArtworkPhotosItem'
import type { ListAuthenticatedUserArtworks200DataItemTagsItem } from './listAuthenticatedUserArtworks200DataItemTagsItem'

export type ListAuthenticatedUserArtworks200DataItem = {
  artwork_comments_count?: number
  artwork_likes_count?: number
  artwork_main_photo_path?: string
  artwork_photos?: ListAuthenticatedUserArtworks200DataItemArtworkPhotosItem[]
  created_at?: string
  description?: string
  id?: number
  status?: string
  tags?: ListAuthenticatedUserArtworks200DataItemTagsItem[]
  title?: string
  updated_at?: string
  user_id?: number
}
