/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListAuthenticatedUserFavoriteArtworks200DataItemArtworkPhotosItem } from './listAuthenticatedUserFavoriteArtworks200DataItemArtworkPhotosItem'
import type { ListAuthenticatedUserFavoriteArtworks200DataItemTagsItem } from './listAuthenticatedUserFavoriteArtworks200DataItemTagsItem'

export type ListAuthenticatedUserFavoriteArtworks200DataItem = {
  artwork_comments_count?: number
  artwork_likes_count?: number
  artwork_main_photo_path?: string
  artwork_photos?: ListAuthenticatedUserFavoriteArtworks200DataItemArtworkPhotosItem[]
  created_at?: string
  description?: string
  id?: number
  status?: string
  tags?: ListAuthenticatedUserFavoriteArtworks200DataItemTagsItem[]
  title?: string
  updated_at?: string
  user_id?: number
}
