/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type ListPublishedArtworksSort =
  (typeof ListPublishedArtworksSort)[keyof typeof ListPublishedArtworksSort]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListPublishedArtworksSort = {
  rising: 'rising',
  new: 'new',
  popular: 'popular',
  trending: 'trending',
} as const
