/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListAuthenticatedUserFollowing200DataItem } from './listAuthenticatedUserFollowing200DataItem'

export type ListAuthenticatedUserFollowing200 = {
  data?: ListAuthenticatedUserFollowing200DataItem[]
}
