/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type ListUsersInclude =
  (typeof ListUsersInclude)[keyof typeof ListUsersInclude]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListUsersInclude = {
  publishedArtworks: 'publishedArtworks',
} as const
