/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListUserPublishedArtworks200MetaLinksItem } from './listUserPublishedArtworks200MetaLinksItem'

export type ListUserPublishedArtworks200Meta = {
  current_page?: number
  from?: number
  last_page?: number
  links?: ListUserPublishedArtworks200MetaLinksItem[]
  path?: string
  per_page?: number
  to?: number
  total?: number
}
