/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type ListAuthenticatedUserFollowingParams = {
  /**
   * The page number to fetch.
   */
  page?: number
  /**
   * The number of items to fetch per page.
   */
  perPage?: number
}
