/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListUsers200DataItem } from './listUsers200DataItem'
import type { ListUsers200Links } from './listUsers200Links'
import type { ListUsers200Meta } from './listUsers200Meta'

export type ListUsers200 = {
  data?: ListUsers200DataItem[]
  links?: ListUsers200Links
  meta?: ListUsers200Meta
}
