/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListUserPublishedArtworks200DataItem } from './listUserPublishedArtworks200DataItem'
import type { ListUserPublishedArtworks200Links } from './listUserPublishedArtworks200Links'
import type { ListUserPublishedArtworks200Meta } from './listUserPublishedArtworks200Meta'

export type ListUserPublishedArtworks200 = {
  data?: ListUserPublishedArtworks200DataItem[]
  links?: ListUserPublishedArtworks200Links
  meta?: ListUserPublishedArtworks200Meta
}
