/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListAuthenticatedUserFavoriteArtworks200MetaLinksItem } from './listAuthenticatedUserFavoriteArtworks200MetaLinksItem'

export type ListAuthenticatedUserFavoriteArtworks200Meta = {
  current_page?: number
  from?: number
  last_page?: number
  links?: ListAuthenticatedUserFavoriteArtworks200MetaLinksItem[]
  path?: string
  per_page?: number
  to?: number
  total?: number
}
