/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListAuthenticatedUserNotifications200OneOfSevenDataDataItem } from './listAuthenticatedUserNotifications200OneOfSevenDataDataItem'
import type { ListAuthenticatedUserNotifications200OneOfSevenDataLinksItem } from './listAuthenticatedUserNotifications200OneOfSevenDataLinksItem'

export type ListAuthenticatedUserNotifications200OneOfSevenData = {
  current_page?: number
  data?: ListAuthenticatedUserNotifications200OneOfSevenDataDataItem[]
  first_page_url?: string
  from?: number
  last_page?: number
  last_page_url?: string
  links?: ListAuthenticatedUserNotifications200OneOfSevenDataLinksItem[]
  next_page_url?: string
  path?: string
  per_page?: number
  prev_page_url?: string
  to?: number
  total?: number
}
