/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListArtistVerificationRequests200DataItemUser } from './listArtistVerificationRequests200DataItemUser'

export type ListArtistVerificationRequests200DataItem = {
  id?: number
  user_id?: number
  status?: string
  reason?: string
  created_at?: string
  updated_at?: string
  user?: ListArtistVerificationRequests200DataItemUser
}
