/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type ListAuthenticatedUserFavoriteArtworks200MetaLinksItem = {
  active?: boolean
  label?: string
  url?: string
}
