/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListUsersInclude } from './listUsersInclude'
import type { ListUsersSort } from './listUsersSort'

export type ListUsersParams = {
  /**
   * Filter artworks by country.
   */
  'filter[country]'?: string
  /**
   * Filter artworks by tag.
   */
  'filter[tag]'?: string
  /**
   * Filter artists by verification status.
   */
  'filter[verified]'?: boolean
  /**
   * Include artworks in the response.
   */
  include?: ListUsersInclude
  /**
   * Search for users by username, first name, or last name.
   */
  searchQuery?: string
  /**
   * Sort artworks by new, or popular.
   */
  sort?: ListUsersSort
  /**
   * The page number to fetch.
   */
  page?: string
  /**
   * The number of records to retrieve per page.
   */
  perPage?: string
}
