/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListAuthenticatedUserNotifications200OneOfSevenDataDataItemDataFollower } from './listAuthenticatedUserNotifications200OneOfSevenDataDataItemDataFollower'

export type ListAuthenticatedUserNotifications200OneOfSevenDataDataItemData = {
  follower?: ListAuthenticatedUserNotifications200OneOfSevenDataDataItemDataFollower
}
