/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type ListAuthenticatedUserNotificationsFilterReadStatus =
  (typeof ListAuthenticatedUserNotificationsFilterReadStatus)[keyof typeof ListAuthenticatedUserNotificationsFilterReadStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListAuthenticatedUserNotificationsFilterReadStatus = {
  read: 'read',
  unread: 'unread',
} as const
