/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */

/**
 * Invalid readStatus
 */
export type ListAuthenticatedUserNotifications400OneOfTwo = {
  message?: string
  status?: number
}
