/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type ListTags200DataItem = {
  id?: number
  name?: string
  created_at?: string
  updated_at?: string
}
