/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type ListUsersSort = (typeof ListUsersSort)[keyof typeof ListUsersSort]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListUsersSort = {
  new: 'new',
  popular: 'popular',
} as const
