/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListPublishedArtworks200DataItem } from './listPublishedArtworks200DataItem'
import type { ListPublishedArtworks200Links } from './listPublishedArtworks200Links'
import type { ListPublishedArtworks200Meta } from './listPublishedArtworks200Meta'

export type ListPublishedArtworks200 = {
  data?: ListPublishedArtworks200DataItem[]
  links?: ListPublishedArtworks200Links
  meta?: ListPublishedArtworks200Meta
}
