/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListAuthenticatedUserFollowing200MetaLinksItem } from './listAuthenticatedUserFollowing200MetaLinksItem'

export type ListAuthenticatedUserFollowing200Meta = {
  current_page?: number
  from?: number
  last_page?: number
  links?: ListAuthenticatedUserFollowing200MetaLinksItem[]
  path?: string
  per_page?: number
  to?: number
  total?: number
}
