/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListPublishedArtworksSort } from './listPublishedArtworksSort'

export type ListPublishedArtworksParams = {
  /**
   * Filter artworks by tag.
   */
  'filter[tag]'?: string
  /**
   * Search for artworks by title or description.
   */
  searchQuery?: string
  /**
   * Sort artworks.
   */
  sort?: ListPublishedArtworksSort
  /**
   * The page number to fetch.
   */
  page?: number
  /**
   * The number of records to fetch per page.
   */
  perPage?: number
}
