/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type ListAuthenticatedUserNotificationsFilterNotificationType =
  (typeof ListAuthenticatedUserNotificationsFilterNotificationType)[keyof typeof ListAuthenticatedUserNotificationsFilterNotificationType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListAuthenticatedUserNotificationsFilterNotificationType = {
  'artist-verification-request': 'artist-verification-request',
  'artist-verification-response': 'artist-verification-response',
  'artwork-comment': 'artwork-comment',
  'artwork-like': 'artwork-like',
  follow: 'follow',
} as const
