/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListAuthenticatedUserNotifications200OneOf } from './listAuthenticatedUserNotifications200OneOf'
import type { ListAuthenticatedUserNotifications200OneOfSeven } from './listAuthenticatedUserNotifications200OneOfSeven'

export type ListAuthenticatedUserNotifications200 =
  | ListAuthenticatedUserNotifications200OneOf
  | ListAuthenticatedUserNotifications200OneOfSeven
