/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type ListUsers200DataItemArtworksItem = {
  artwork_comments_count?: number
  artwork_likes_count?: number
  artwork_main_photo_path?: string
  created_at?: string
  description?: string
  id?: number
  status?: string
  title?: string
  updated_at?: string
  user_id?: number
}
