/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListArtistVerificationRequests200DataItem } from './listArtistVerificationRequests200DataItem'
import type { ListArtistVerificationRequests200Links } from './listArtistVerificationRequests200Links'
import type { ListArtistVerificationRequests200Meta } from './listArtistVerificationRequests200Meta'

export type ListArtistVerificationRequests200 = {
  data?: ListArtistVerificationRequests200DataItem[]
  links?: ListArtistVerificationRequests200Links
  meta?: ListArtistVerificationRequests200Meta
}
