/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListUserReceivedLikesCountByTag200DataItem } from './listUserReceivedLikesCountByTag200DataItem'

export type ListUserReceivedLikesCountByTag200 = {
  data?: ListUserReceivedLikesCountByTag200DataItem[]
  message?: string
  status?: number
}
