/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type ListAuthenticatedUserArtworks200DataItemArtworkPhotosItem = {
  id?: number
  path?: string
  is_main?: number
  artwork_id?: number
  created_at?: string
  updated_at?: string
}
