/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ListAuthenticatedUserFavoriteArtworks200DataItemTagsItemPivot } from './listAuthenticatedUserFavoriteArtworks200DataItemTagsItemPivot'

export type ListAuthenticatedUserFavoriteArtworks200DataItemTagsItem = {
  id?: number
  name?: string
  created_at?: string
  updated_at?: string
  pivot?: ListAuthenticatedUserFavoriteArtworks200DataItemTagsItemPivot
}
