/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { MarkArtworkAsFavorite200Data } from './markArtworkAsFavorite200Data'

export type MarkArtworkAsFavorite200 = {
  data?: MarkArtworkAsFavorite200Data
}
