/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { PostArtworkComment200Data } from './postArtworkComment200Data'

export type PostArtworkComment200 = {
  data?: PostArtworkComment200Data
}
