/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type PostArtworkComment200Data = {
  id?: number
  comment_text?: string
  artwork_id?: number
  user_id?: number
  created_at?: string
  updated_at?: string
}
