/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { PublishArtwork200Data } from './publishArtwork200Data'

export type PublishArtwork200 = {
  data?: PublishArtwork200Data
}
