/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type ReplaceArtworkPhotoPathBody = {
  /**
   * The file of the photo. Must be an image. Must not be greater than 5000000 kilobytes.
   */
  photo: Blob
}
