/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ResetPassword200Data } from './resetPassword200Data'

export type ResetPassword200 = {
  message?: string
  data?: ResetPassword200Data
  status?: number
}
