/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type ResetPasswordBody = {
  /**
   * The token sent to the user email.
   */
  token: string
  /**
   * The email of the user. Must be a valid email address. The <code>email</code> of an existing record in the users table.
   */
  email: string
  /**
   * The new password of the user. Must be at least 8 characters.
   */
  password: string
}
