/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */

/**
 * The status of the artist verification request.
 */
export type ReviewArtistVerificationRequestBodyStatus =
  (typeof ReviewArtistVerificationRequestBodyStatus)[keyof typeof ReviewArtistVerificationRequestBodyStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReviewArtistVerificationRequestBodyStatus = {
  approved: 'approved',
  rejected: 'rejected',
} as const
