/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ReviewArtistVerificationRequest200Data } from './reviewArtistVerificationRequest200Data'

export type ReviewArtistVerificationRequest200 = {
  data?: ReviewArtistVerificationRequest200Data
}
