/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type ReviewArtistVerificationRequestBody = {
  /**
   * The status of the artist verification request.
   */
  status?: string
  /**
   * The reason for rejecting the artist verification request. This field is required when <code>status</code> is <code>rejected</code>.
   */
  reason?: string
}
