/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type SendResetPasswordLinkBody = {
  /**
   * The email address of the user. Must be unique. Must be a valid email address. The <code>email</code> of an existing record in the users table.
   */
  email: string
}
