/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { SendResetPasswordLink200Data } from './sendResetPasswordLink200Data'

export type SendResetPasswordLink200 = {
  message?: string
  data?: SendResetPasswordLink200Data
  status?: number
}
