/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ShowPublishedArtwork200DataItemArtworkCommentsItemUser } from './showPublishedArtwork200DataItemArtworkCommentsItemUser'

export type ShowPublishedArtwork200DataItemArtworkCommentsItem = {
  artwork_id?: number
  comment_text?: string
  created_at?: string
  id?: number
  updated_at?: string
  user?: ShowPublishedArtwork200DataItemArtworkCommentsItemUser
  user_id?: number
}
