/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type ShowPublishedArtwork200DataItemArtworkCommentsItemUser = {
  id?: number
  username?: string
  first_name?: string
  last_name?: string
  email?: string
  country?: string
  bio?: string
  photo?: string
  artist_verified_at?: string
  email_verified_at?: string
  role?: string
  created_at?: string
  updated_at?: string
}
