/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ShowPublishedArtwork200DataTagsItemPivot } from './showPublishedArtwork200DataTagsItemPivot'

export type ShowPublishedArtwork200DataTagsItem = {
  id?: number
  name?: string
  created_at?: string
  updated_at?: string
  pivot?: ShowPublishedArtwork200DataTagsItemPivot
}
