/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ShowAuthenticatedUserArtwork200DataArtworkPhotosItem } from './showAuthenticatedUserArtwork200DataArtworkPhotosItem'
import type { ShowAuthenticatedUserArtwork200DataTagsItem } from './showAuthenticatedUserArtwork200DataTagsItem'

export type ShowAuthenticatedUserArtwork200Data = {
  id?: number
  title?: string
  description?: string
  status?: string
  user_id?: number
  created_at?: string
  updated_at?: string
  artwork_likes_count?: number
  artwork_comments_count?: number
  artwork_main_photo_path?: string
  artwork_photos?: ShowAuthenticatedUserArtwork200DataArtworkPhotosItem[]
  tags?: ShowAuthenticatedUserArtwork200DataTagsItem[]
}
