/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ShowAuthenticatedUserArtwork200DataTagsItemPivot } from './showAuthenticatedUserArtwork200DataTagsItemPivot'

export type ShowAuthenticatedUserArtwork200DataTagsItem = {
  id?: number
  name?: string
  created_at?: string
  updated_at?: string
  pivot?: ShowAuthenticatedUserArtwork200DataTagsItemPivot
}
