/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ShowUser200Data } from './showUser200Data'

export type ShowUser200 = {
  data?: ShowUser200Data
}
