/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ShowAuthenticatedUserArtwork200Data } from './showAuthenticatedUserArtwork200Data'

export type ShowAuthenticatedUserArtwork200 = {
  data?: ShowAuthenticatedUserArtwork200Data
}
