/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ShowPublishedArtwork200DataItemArtworkLikesItemUser } from './showPublishedArtwork200DataItemArtworkLikesItemUser'

export type ShowPublishedArtwork200DataItemArtworkLikesItem = {
  artwork_id?: number
  created_at?: string
  id?: number
  updated_at?: string
  user?: ShowPublishedArtwork200DataItemArtworkLikesItemUser
  user_id?: number
}
