/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ShowUserById200Data } from './showUserById200Data'

export type ShowUserById200 = {
  data?: ShowUserById200Data
}
