/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ShowPublishedArtwork200DataUser } from './showPublishedArtwork200DataUser'
import type { ShowPublishedArtwork200DataArtworkPhotosItem } from './showPublishedArtwork200DataArtworkPhotosItem'
import type { ShowPublishedArtwork200DataArtworkCommentsItem } from './showPublishedArtwork200DataArtworkCommentsItem'
import type { ShowPublishedArtwork200DataArtworkLikesItem } from './showPublishedArtwork200DataArtworkLikesItem'
import type { ShowPublishedArtwork200DataTagsItem } from './showPublishedArtwork200DataTagsItem'

export type ShowPublishedArtwork200Data = {
  id?: number
  title?: string
  description?: string
  status?: string
  user_id?: number
  created_at?: string
  updated_at?: string
  artwork_likes_count?: number
  artwork_comments_count?: number
  artwork_main_photo_path?: string
  user?: ShowPublishedArtwork200DataUser
  artwork_photos?: ShowPublishedArtwork200DataArtworkPhotosItem[]
  artwork_comments?: ShowPublishedArtwork200DataArtworkCommentsItem[]
  artwork_likes?: ShowPublishedArtwork200DataArtworkLikesItem[]
  tags?: ShowPublishedArtwork200DataTagsItem[]
}
