/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type ShowPublishedArtwork200DataTagsItemPivot = {
  artwork_id?: number
  tag_id?: number
}
