/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ShowPublishedArtwork200DataItemTagsItemPivot } from './showPublishedArtwork200DataItemTagsItemPivot'

export type ShowPublishedArtwork200DataItemTagsItem = {
  created_at?: string
  id?: number
  name?: string
  pivot?: ShowPublishedArtwork200DataItemTagsItemPivot
  updated_at?: string
}
