/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ShowPublishedArtwork200DataItemArtworkCommentsItem } from './showPublishedArtwork200DataItemArtworkCommentsItem'
import type { ShowPublishedArtwork200DataItemArtworkLikesItem } from './showPublishedArtwork200DataItemArtworkLikesItem'
import type { ShowPublishedArtwork200DataItemArtworkPhotosItem } from './showPublishedArtwork200DataItemArtworkPhotosItem'
import type { ShowPublishedArtwork200DataItemTagsItem } from './showPublishedArtwork200DataItemTagsItem'
import type { ShowPublishedArtwork200DataItemUser } from './showPublishedArtwork200DataItemUser'

export type ShowPublishedArtwork200DataItem = {
  artwork_comments?: ShowPublishedArtwork200DataItemArtworkCommentsItem[]
  artwork_comments_count?: number
  artwork_likes?: ShowPublishedArtwork200DataItemArtworkLikesItem[]
  artwork_likes_count?: number
  artwork_main_photo_path?: string
  artwork_photos?: ShowPublishedArtwork200DataItemArtworkPhotosItem[]
  created_at?: string
  description?: string
  id?: number
  status?: string
  tags?: ShowPublishedArtwork200DataItemTagsItem[]
  title?: string
  updated_at?: string
  user?: ShowPublishedArtwork200DataItemUser
  user_id?: number
}
