/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type ShowUser200Data = {
  artist_verified_at?: string
  bio?: string
  country?: string
  created_at?: string
  email?: string
  email_verified_at?: string
  first_name?: string
  id?: number
  last_name?: string
  photo?: string
  role?: string
  updated_at?: string
  username?: string
}
