/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { ShowPublishedArtwork200DataItem } from './showPublishedArtwork200DataItem'

export type ShowPublishedArtwork200 = {
  data?: ShowPublishedArtwork200DataItem[]
}
