/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type ShowPublishedArtwork200DataItemArtworkPhotosItem = {
  artwork_id?: number
  created_at?: string
  id?: number
  is_main?: number
  path?: string
  updated_at?: string
}
