/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { SignIn200Data } from './signIn200Data'

export type SignIn200 = {
  data?: SignIn200Data
  message?: string
  status?: number
}
