/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { SignUp200Data } from './signUp200Data'

export type SignUp200 = {
  message?: string
  data?: SignUp200Data
  status?: number
}
