/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type SignInBody = {
  /**
   * The email address of the user attempting to sign in. Must be a valid email address.
   */
  email: string
  /**
   * The password associated with the user account.
   */
  password: string
}
