/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type SignUpBody = {
  /**
   * The email address of the user. Must be unique. Must be a valid email address.
   */
  email: string
  /**
   * A secure password for the user. Must be at least 8 characters long. Must be at least 8 characters.
   */
  password: string
  /**
   * A unique username for the user.
   */
  username: string
}
