/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type SubmitArtistVerificationRequest200Data = {
  id?: number
  user_id?: number
  status?: string
  reason?: string
  created_at?: string
  updated_at?: string
}
