/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { SubmitArtistVerificationRequest200Data } from './submitArtistVerificationRequest200Data'

export type SubmitArtistVerificationRequest200 = {
  data?: SubmitArtistVerificationRequest200Data
}
