/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { SubmitArtistVerificationRequest400OneOf } from './submitArtistVerificationRequest400OneOf'
import type { SubmitArtistVerificationRequest400OneOfTwo } from './submitArtistVerificationRequest400OneOfTwo'
import type { SubmitArtistVerificationRequest400OneOfThree } from './submitArtistVerificationRequest400OneOfThree'
import type { SubmitArtistVerificationRequest400OneOfFour } from './submitArtistVerificationRequest400OneOfFour'

export type SubmitArtistVerificationRequest400 =
  | SubmitArtistVerificationRequest400OneOf
  | SubmitArtistVerificationRequest400OneOfTwo
  | SubmitArtistVerificationRequest400OneOfThree
  | SubmitArtistVerificationRequest400OneOfFour
