/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { UnfollowUser404OneOf } from './unfollowUser404OneOf'
import type { UnfollowUser404OneOfTwo } from './unfollowUser404OneOfTwo'

export type UnfollowUser404 = UnfollowUser404OneOf | UnfollowUser404OneOfTwo
