/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */

/**
 * User not found
 */
export type UnfollowUser404OneOf = {
  message?: string
  status?: number
}
