/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type UpdateAuthenticatedUserBody = {
  /**
   * The bio of the user.
   */
  bio?: string
  /**
   * The country of the user. The <code>name</code> of an existing record in the countries table. Must not be greater than 255 characters.
   */
  country?: string
  /**
   * The email of the user. Must be a valid email address.
   */
  email?: string
  /**
   * The first name of the user. Must not be greater than 255 characters.
   */
  first_name?: string
  /**
   * The last name of the user. Must not be greater than 255 characters.
   */
  last_name?: string
  /**
   * The photo of the user. Must be an image. Must not be greater than 2048 kilobytes.
   */
  photo?: Blob
  /**
   * The username of the user. Must not be greater than 255 characters.
   */
  username?: string
}
