/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type UpdateArtworkDraftBody = {
  /**
   * The title of the artwork. Must be at least 3 characters. Must not be greater than 255 characters.
   */
  title?: string
  /**
   * The description of the artwork.
   */
  description?: string
  /** The tag of the artwork. The <code>name</code> of an existing record in the tags table. */
  tags?: string[]
}
