/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateArtworkComment200Data } from './updateArtworkComment200Data'

export type UpdateArtworkComment200 = {
  data?: UpdateArtworkComment200Data
}
