/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateArtworkDraft200Data } from './updateArtworkDraft200Data'

export type UpdateArtworkDraft200 = {
  data?: UpdateArtworkDraft200Data
}
