/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateAuthenticatedUser200Data } from './updateAuthenticatedUser200Data'

export type UpdateAuthenticatedUser200 = {
  data?: UpdateAuthenticatedUser200Data
}
