/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { UploadArtworkPhotos200DataItem } from './uploadArtworkPhotos200DataItem'

export type UploadArtworkPhotos200 = {
  data?: UploadArtworkPhotos200DataItem[]
}
