/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */

export type UploadArtworkPhotosBody = {
  /** A photo of the artwork. Must be an image. Must not be greater than 2048 kilobytes. */
  photos: Blob[]
}
