/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import type { VerifyEmailCode400OneOf } from './verifyEmailCode400OneOf'
import type { VerifyEmailCode400OneOfTwo } from './verifyEmailCode400OneOfTwo'

export type VerifyEmailCode400 =
  | VerifyEmailCode400OneOf
  | VerifyEmailCode400OneOfTwo
