/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * ArtHive API Documentation
 * ArtHive API Documentation
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod'

/**
 * Retrieve a list of tags used by a user's published artworks
 * @summary List User Artwork Tags
 */
export const listUserArtworkTagsResponse = zod.object({
  data: zod
    .array(
      zod.object({
        id: zod.number().optional(),
        name: zod.string().optional(),
      })
    )
    .optional(),
  message: zod.string().optional(),
  status: zod.number().optional(),
})

/**
 * Retrieve a list of all tags
 * @summary List Tags
 */
export const listTagsResponse = zod.object({
  data: zod
    .array(
      zod.object({
        id: zod.number().optional(),
        name: zod.string().optional(),
        created_at: zod.string().optional(),
        updated_at: zod.string().optional(),
      })
    )
    .optional(),
})
